user:
  name: 江平 # 昵称
  first_name: 平 # 名字
  last_name: 江 # 姓氏
  email: kjm_2021@163.com # 邮箱
  domain: https://jx0628.github.io # 域名
  avatar: /assets/images/avatar.png # 头像
  describe: 网站简介。 #网站简介
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。 #友链交换规则

theme:
  switch: true # 主题切换按钮
  default: style-light # style-light style-dark 主题默认模式

favicon:
  logo: /assets/images/favicon.ico
  icon16: /assets/images/favicon-16x16.png
  icon32: /assets/images/favicon-32x32.png
  appleTouchIcon: /assets/images/favicon-32x32.png
  webmanifest: /site.webmanifest
  visibilitychange: false # 是否在离开窗口时切换标题显示
  hidden: /assets/images/favicon.ico # 离开窗口时显示图标
  showText: # 激活窗口时显示文字
  hideText: # 离开窗口显示文字

assets:
  third_party_provider: https://npm.elemecdn.com # 三方插件 JS 的 CDN 配置

sidebar:
  # 打字动画
  typedTextPrefix:
  typedText: [ "越努力，越幸运！" ]
  # 图标及地址配置
  social: # 社交地址
    - name: github
      icon: fab fa-github-square
      url: https://jx0628.github.io
  # 个人信息
  info:
    - key: 年龄
      val: 18+

# 顶部目录
top_bars:
  - title: 首页
    url: /
  - title: 归档
    url: /archives/
    noswup: true
  - title: 分类
    url: /categories/
    noswup: true
  - title: 相册
    url: /album/
    noswup: true
  - title: 关于
    url: /about/
    noswup: true


banner:
  default:
    type: img
    bgurl: /assets/images/banner-bgc-image.png
    bannerText: Don't give up when you are able to fly.
    position: top
    fit: cover
  index:
    type: img
    bgurl: /assets/images/banner-bgc-image.png
    bannerTitle: 宠辱不惊，</br>闲看庭前花开花落。
    bannerText: Don't give up when you are able to fly.
  archive:
    type: img
    bgurl: /assets/images/banner-bgc-image.png
    bannerTitle: 宠辱不惊，</br>闲看庭前花开花落。
    bannerText: Don't give up when you are able to fly.
  album:
    type: img
    bgurl: /assets/images/banner-bgc-image.png
    bannerTitle: 宠辱不惊，</br>闲看庭前花开花落。
    bannerText: Don't give up when you are able to fly.
  about:
    type: img
    bgurl: /assets/images/banner-bgc-image.png
    bannerTitle: 宠辱不惊，</br>闲看庭前花开花落。
    bannerText: Don't give up when you are able to fly.

#    banner:
#      use_cover: false
#      default:
#        type: img
#        bgurl: /img/banner.png
#        bannerText: Hi my new friend!
#        position: top
#        fit: cover
#      index:
#        bannerTitle: 树深时见鹿，<br>溪午不闻钟。
#        bannerText: Hi my new friend!
#        videoUrl:
#      archive:
#        bannerTitle: 云间连下榻，<br>天上接行杯。
#        bannerText: The article archive
#      links:
#        bannerTitle: 莫愁前路无知己，<br>天下谁人不识君。
#        bannerText: A link to a friend's website
#      comment:
#        bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
#        bannerText: The magic tree hole
#      about:
#        bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
#        bannerText: About me

toc:
  enable: true
  list_number: true
  post_title: false
  max_depth: 3
  min_depth: 1

footer:
  powered:
    enable: false
  beian:
    enable: false
    icp:
  copyrightYear: 2024
  live_time:
    enable: false
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00
  custom_text: '去留无意，漫随天外云卷云舒'

#layout:
#  footer: async/footer/footer

# 图片封面 -- 随机设置
cover:
  type: random
  default:
    - https://img95.699pic.com/photo/40045/2675.jpg_wh300.jpg
    - https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
