comment:
  gitalk:
    enable: true
    owner: Jx0629
    admin: Kjm
    repo: https://jx0628.github.io/
    ClientID:
    ClientSecret:
    labels: 'gitalk'
    distractionFreeMode: true
socialList:
  - name: telegram
    url: https://jx0628.github.io/
  - name: github
    url: https://jx0628.github.io/
  - name: mail
    url: https://jx0628.github.io/
highlight:
  light: https://cdn.staticfile.org/highlight.js/11.5.0/styles/github.min.css
  dark: https://cdn.staticfile.org/highlight.js/11.5.0/styles/github-dark.min.css
copyright:
  enable: true
  license: ''